scripts/wl-present: improve pipectl-shim
- Make pipectl-shim emit the same error messages as pipectl
- Make pipectl-shim check for an active pipe before running
- Make pipectl-shim always fill the pipe with an empty line on start.
  This allows 'tail -f' to correctly identify when the output end of its
  pipe has closed.

Fixes #51.

diff --git a/scripts/wl-present b/scripts/wl-present
--- a/scripts/wl-present
+++ b/scripts/wl-present
@@ -76,8 +76,18 @@ pipectl-shim() {
 
     PIPE="$PIPEPATH/$PIPENAME"
     case "$MODE" in
-        "in") test -p "$PIPE" && cat > "$PIPE";;
-        "out") rm -f "$PIPE"; mkfifo "$PIPE"; tail -f "$PIPE"; rm -f "$PIPE";;
+        "in") if [[ ! -p "$PIPE" ]]; then
+                echo "error: could not open pipe at '$PIPE': No such file or directory" >&2
+                return 1
+            else
+                cat > "$PIPE"
+            fi;;
+        "out") if [[ -p "$PIPE" ]]; then
+                echo "error: cannot create pipe at '$PIPE': File exists" >&2
+                return 1
+            else
+                mkfifo "$PIPE"; (tail -f "$PIPE" & echo > "$PIPE"; wait); rm -f "$PIPE"
+            fi;;
     esac
 }
 
